---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# pdec-analysis-2

This R project implements the analyses for 
"PPM-Decay: A Computational Model of Auditory Prediction with Memory Decay"
by Peter M. C. Harrison, Roberta Bianco, Maria Chait, and Marcus T. Pearce.

## Installation

These scripts depend on various R packages which can be installed 
with the following commands (Internet connection required):

```r
install.packages(c(
`r paste(paste("'", readLines("packages.txt"), "'", sep = ""), collapse = ",\n ")`
))
devtools::install_github("pmcharrison/ppm@v0.1.1")
devtools::install_github("pmcharrison/hrep@v0.11.0")
devtools::install_github("pmcharrison/hcorp@v0.6.2")
```

## Usage

a) Open this R project by opening `pdec-analysis-2.proj` in RStudio.
b) Compile the behavioral response data by running `src/0-compile/0-compile.R` in R.
c) Conduct the behavioral modeling by running `src/1-analyse/1-analyse.R` in R.
d) Create the summary behavioral analyses by running `src/2-summarise/2-summarise.R` in R.
e) Conduct the simulation experiments by running `src/1-experiments.R` in R.
f) Plot the simulation experiments by running `src/2-plots.R` in R.

## Contents

- `archive` - Contains archived outputs from Roberta's initial exploration of the perceptual data.
- `input` - Raw input files.
- `output` - Output files generated by these scripts.
- `packages.txt` - List of CRAN dependencies.
- `pdec-analysis-2.Rproj` - R project file.
- `README.Rmd` - Programmatically generates the README file.
- `README.md` - The README file.
- `src` - Contains the R source code.
