library(tidyverse)
library(checkmate)
library(futile.logger)
library(memoise)
library(glue)
library(withr)
loadNamespace("R.utils")
loadNamespace("plyr")
theme_set(theme_classic())

for (f in list.files("src/1-analyse/functions/", full.names = TRUE))
  source(f)

dat <- readRDS("output/dat-response.rds")

model_detail <- model(dat = dat, downsample = 2)
model_summary <- summarise_models(model_detail)
subj_summary <- get_subj_summary(dat)
combined_summary <- get_combined_summary(model_summary, subj_summary)
print(plot(combined_summary))
